/**
 * Build script to generate config.js from environment variables
 * 
 * For local development:
 * - Uses .env file via dotenv
 * 
 * For Vercel/production:
 * - Uses environment variables set in Vercel dashboard
 * 
 * Run this script using: node build-config.js
 * Or: npm run build
 */

// Try to load .env file for local development (won't exist in production)
try {
    require('dotenv').config();
} catch (e) {
    // dotenv not available or .env doesn't exist - use environment variables directly
    console.log('Using environment variables directly (production mode)');
}

const fs = require('fs');
const path = require('path');

// Get API key from environment variables (works in both local and Vercel)
const apiKey = process.env.GEMINI_API_KEY;

if (!apiKey) {
    console.error('Error: GEMINI_API_KEY not found!');
    console.error('Local: Please create a .env file with GEMINI_API_KEY=your-api-key');
    console.error('Vercel: Please set GEMINI_API_KEY in Vercel dashboard under Project Settings > Environment Variables');
    process.exit(1);
}

// Generate config.js
const configContent = `// API Configuration
// This file is auto-generated from .env file using dotenv
// DO NOT EDIT THIS FILE MANUALLY - edit .env instead
// Run: npm run build (or node build-config.js) to regenerate

const CONFIG = {
    GEMINI_API_KEY: '${apiKey}'
};
`;

// Write config.js
const configPath = path.join(__dirname, 'config.js');
fs.writeFileSync(configPath, configContent, 'utf8');

console.log('✓ Successfully generated config.js from .env file');
console.log('✓ API key has been loaded and configured');

